# Generated by Django 3.2 on 2021-05-03 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlassType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.CharField(max_length=5)),
                ('breadth', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=25)),
                ('quantity', models.CharField(max_length=5)),
                ('glass_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.glasstype')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.size')),
            ],
        ),
        migrations.CreateModel(
            name='OffCutProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=25)),
                ('length', models.CharField(max_length=5)),
                ('breadth', models.CharField(max_length=5)),
                ('quantity', models.CharField(default='0', max_length=5)),
                ('glass_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.glasstype')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glass_type', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=25)),
                ('size', models.CharField(default='None', max_length=15)),
                ('initial_quantity', models.CharField(max_length=5)),
                ('in_quantity', models.CharField(max_length=5)),
                ('used_quantity', models.CharField(max_length=5)),
                ('left_quantity', models.CharField(max_length=5)),
                ('date', models.CharField(max_length=15)),
                ('offcut', models.BooleanField(default=False)),
                ('remarks', models.CharField(default='No Remark', max_length=2500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
